[settings.npm]
package_manager = "bun"

[tools]
"aqua:modem-dev/hunk" = "latest"
act = "latest"
aws-cli = "latest"
bun = "latest"
caddy = "latest"
claude = "latest"
cloudflared = "latest"
codex = "latest"
d2 = "latest"
delta = "latest"
fd = "latest"
flyctl = "latest"
fzf = "latest"
gh = "latest"
herdr = "latest"
infisical = "latest"
k9s = "latest"
lazygit = "latest"
neonctl = "latest"
neovim = "latest"
node = "26.7.0"
"npm:@withgraphite/graphite-cli" = "stable"
"npm:open-computer-use" = "0.3.2"
op = "latest"
pi = "latest"
rust = "latest"
tree-sitter = "latest"
worktrunk = "latest"
zig = "latest"
zoxide = "latest"
